version: 1.5.{build}

image: Visual Studio 2017

configuration: Release

before_build:
- cmd: nuget restore Renci.SshNet.Async.sln

build:
  project: Renci.SshNet.Async.sln

artifacts:
  - path: '**\*.nupkg'